// getGraph() 실패 시(백엔드 미준비) 폴백으로 쓰는 목업. graph prop이 오면 무시됨
export const MOCK_GRAPH = {
  nodes: [
    { id: 'n1', type: 'number', label: '010-1234-5678', cluster: 0 },
    { id: 'n2', type: 'number', label: '010-2222-3333', cluster: 0 },
    { id: 'u1', type: 'url', label: 'bit.ly/abcxyz', cluster: 0 },
    { id: 'u2', type: 'url', label: 'short.url/kk22', cluster: 0 },
    { id: 'p1', type: 'phrase', label: '택배 배송 조회', cluster: 0 },
    { id: 'n3', type: 'number', label: '02-987-6543', cluster: 1 },
    { id: 'n4', type: 'number', label: '070-1111-2222', cluster: 1 },
    { id: 'u3', type: 'url', label: 'phish-bank.kr', cluster: 1 },
    { id: 'p2', type: 'phrase', label: '계좌 정지 안내', cluster: 1 },
    { id: 'p3', type: 'phrase', label: '본인인증 필요', cluster: 1 },
    { id: 'n5', type: 'number', label: '050-4444-5555', cluster: 2 },
    { id: 'u4', type: 'url', label: 'gov-refund.net', cluster: 2 },
    { id: 'u5', type: 'url', label: 'tax-refund.kr', cluster: 2 },
    { id: 'p4', type: 'phrase', label: '환급금 조회', cluster: 2 },
  ],
  edges: [
    { source: 'n1', target: 'u1' },
    { source: 'n1', target: 'p1' },
    { source: 'n2', target: 'u1' },
    { source: 'n2', target: 'u2' },
    { source: 'u2', target: 'p1' },
    { source: 'n3', target: 'u3' },
    { source: 'n3', target: 'p2' },
    { source: 'n4', target: 'u3' },
    { source: 'n4', target: 'p3' },
    { source: 'p2', target: 'p3' },
    { source: 'n5', target: 'u4' },
    { source: 'n5', target: 'u5' },
    { source: 'u4', target: 'p4' },
    { source: 'u5', target: 'p4' },
  ],
  cluster_count: 3,
}
